services:
  - type: web
    name: portofolio-brilianti
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true     # Render auto-generate secret key yang aman
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
